[Interface]
PrivateKey = aWNlc2xhYi10dW5uZWwtZml4dHVyZS1wcml2LWZyb20=
Address = 10.67.0.1/30
Table = off
Jc = 4
Jmin = 80
Jmax = 400
S1 = 20
S2 = 30
S3 = 12
S4 = 7
H1 = 1111
H2 = 2222
H3 = 3333
H4 = 4444

[Peer]
PublicKey = aWNlc2xhYi10dW5uZWwtZml4dHVyZS1wdWItdG8hISE=
AllowedIPs = 10.67.0.2/32
Endpoint = exit.example.com:27000
PersistentKeepalive = 25
