[Interface]
PrivateKey = cliPriv64
Address = 10.67.67.2/32
MTU = 1376
Jc = 3
Jmin = 65
Jmax = 146
S1 = 27
S2 = 117
S3 = 49
S4 = 46
H1 = 1707668061
H2 = 1777446261
H3 = 1485019533
H4 = 1891020874
I1 = <b 0x0001><b 0x000c><b 0x2112a442><r 12><b 0x8022><b 0x0008><rc 8>
I2 = <r 196>
HeaderProtectionKey = CzpTkdFCW89NLCYwz9m1dvdo77wiWYFfNgcIsbPOshM=
ContentPaddingAddition = 1-55
RekeyAfterTime = 113-142
RekeyTimeout = 4-7
RejectAfterTime = 226-272
KeepaliveTimeout = 9-17
MaxHandshakeAttempts = 12-19
RandomTrailers = on

[Peer]
PublicKey = srvPub64
AllowedIPs = 0.0.0.0/0, ::/0
Endpoint = de.example.com:51830
PersistentKeepalive = 25
